### ISSUE TITLE
Question regarding GPIO22

### ISSUE THREAD

**Issue by pchaploutskii** [gregmac/Genmon-ESP32-Serial-Bridge#13]
Hey, @gregmac thank you so much for putting this together! Was so thrilled when I found this repo.
What was the issue with GPIO3? Not sure Why I am not receiving any data from my generator at all, and curious what was your solution, although haven't tried yet GPIO22 just yet.

**Comment by gregmac** [comment]
I think it was a bad solder pad on the MAX3232 board, probably from overheating it.

For no data, check out the local web interface the ESP32 is running -- it should show a dump of any RS232 data it sees. You should at least see Genmon sending a request every few seconds.

Second to that check your MAX3232 connections (good solder connection, TTL/232 side, send/receive direction, and same side of board).

With it disconnected from the generator, if you connect the RS232 send and receive lines together, you should be able to see anything you send on the ESP serial echo'd back directly. With genmon connecting, you'll be able to see the same data it sends being dumped back in (which genmon won't understand), verifying the connections on at least that side are ok.

**Comment by pchaploutskii** [comment]
thank you, Greg, appreciate it.
Will try it out, but I think I am good to close

**Comment by pchaploutskii** [comment]
hey, @gregmac after several tries & fails I end up using the GPIO22 pin, not sure why GPIO03 won't work for me either.
Anyway, thank you for putting this together
