### ISSUE TITLE
ESPHome syntax has changed.

### ISSUE THREAD

**Issue by chriskinal** [gregmac/Genmon-ESP32-Serial-Bridge#20]
ESPhome has deprecated the "dallas" platform in favor of one_wire. esphome\generator.yamle needs to be updated .

New section below.

one_wire:
  - platform: gpio
    pin: GPIO4 # GPIO4 (pin 24)

sensor:
  - platform: dallas_temp
    address: 0x65000006a8115937
    name: "Generator Ambient Temperature"
  - platform: dallas_temp
    address: 0x080000056e145237
    name: "Generator Engine Temperature"
    
  - platform: wifi_signal
    name: "$name WiFi Signal Sensor"
    update_interval: 60s

**Comment by gmn42** [comment]
FYI, PR #19 takes care of this, hopefully it get will get merged.

**Comment by chriskinal** [comment]
Thanks. I did not see the PR.
